# Generated by Django 3.2.5 on 2021-07-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('type_one', models.CharField(blank=True, choices=[('BUG', 'Bug'), ('DAR', 'Dark'), ('DRA', 'Dragon'), ('ELE', 'Electric'), ('FAI', 'Fairy'), ('FIG', 'Fighting'), ('FIR', 'Fire'), ('FLY', 'Flying'), ('GHO', 'Ghost'), ('GRA', 'Grass'), ('GRO', 'Ground'), ('ICE', 'Ice'), ('NOR', 'Normal'), ('POI', 'Poison'), ('PSY', 'Psychic'), ('ROC', 'Rock'), ('STE', 'Steel'), ('WAT', 'Water')], max_length=3, null=True)),
                ('type_two', models.CharField(blank=True, choices=[('BUG', 'Bug'), ('DAR', 'Dark'), ('DRA', 'Dragon'), ('ELE', 'Electric'), ('FAI', 'Fairy'), ('FIG', 'Fighting'), ('FIR', 'Fire'), ('FLY', 'Flying'), ('GHO', 'Ghost'), ('GRA', 'Grass'), ('GRO', 'Ground'), ('ICE', 'Ice'), ('NOR', 'Normal'), ('POI', 'Poison'), ('PSY', 'Psychic'), ('ROC', 'Rock'), ('STE', 'Steel'), ('WAT', 'Water')], max_length=3, null=True)),
                ('total', models.PositiveIntegerField(default=0)),
                ('hp', models.PositiveIntegerField(default=0)),
                ('attack', models.PositiveIntegerField(default=0)),
                ('defense', models.PositiveIntegerField(default=0)),
                ('sp_attack', models.PositiveIntegerField(default=0)),
                ('sp_def', models.PositiveIntegerField(default=0)),
                ('speed', models.PositiveIntegerField(default=0)),
                ('generation', models.PositiveIntegerField(default=0)),
                ('legendary', models.BooleanField(default=False)),
            ],
        ),
    ]
